services:
  backend:
    build: ./backend
    container_name: learnloop-backend
    ports:
      - "5050:5000"  # Host:Container (optional but useful for testing)
    env_file:
      - ./backend/.env
    volumes:
      # bind-mount the host file into the container
      - ./backend/conversations.db:/app/conversations.db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: learnloop-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped